spring.application.name=flight-scout

# Server
server.port=9002

# PostgreSQL (Docker - port 5434 ?eby nie kolidowa? z Finance Trackerem)
spring.datasource.url=jdbc:postgresql://localhost:5434/flightscoutdb
spring.datasource.username=postgres
spring.datasource.password=postgres

# JPA
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=false

# Liquibase
#spring.liquibase.enabled=true
#spring.liquibase.change-log=db/changelog/changelog-master.xml
# Liquibase
spring.liquibase.change-log=classpath:db/changelog/changelog-master.xml

spring.liquibase.enabled=true
logging.level.liquibase=DEBUG
#logging.level.org.springframework.boot.autoconfigure=DEBUG


# Redis
spring.data.redis.host=localhost
spring.data.redis.port=6380
spring.cache.type=redis
spring.cache.redis.time-to-live=1800000
spring.data.redis.repositories.enabled=false

# Kafka
spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.consumer.group-id=flight-scout-group
spring.kafka.consumer.auto-offset-reset=earliest

# JWT
jwt.secret=FlightScoutSecretKeyForJWTTokenGenerationMinimum48Chars
jwt.expiration=86400000

# Amadeus API
amadeus.api.key=YOUR_API_KEY
amadeus.api.secret=YOUR_API_SECRET
amadeus.api.url=https://test.api.amadeus.com

# Swagger
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.enabled=true
springdoc.api-docs.enabled=true

# Logging
logging.charset.console=UTF-8
logging.charset.file=UTF-8

# Async
spring.task.execution.pool.core-size=5
spring.task.execution.pool.max-size=10